---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: ../../roles
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  name: chef_solo

platforms:
  - name: ubuntu-14.04
## 20160119 disabling centos platform because ansible v2 out and epel still in 1.9.4
#  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:

