---

#
### template as ansible template conf file?
### (old nagios/nrpe client way)
#

- name: Debug
  debug: var=ansible_fqdn
- name: Debug
  debug: var=inventory_hostname
- name: Debug
  debug: var=icinga2_server
- name: Client nrpe config on Icinga server
  template:
    src: hosts-template.conf
    dest: "/etc/icinga2/conf.d/hosts-icinga2server-{{ ansible_fqdn }}.conf"
    mode: '0644'
  delegate_to: "{{ icinga2_server }}"
  notify:
    - restart icinga2
  when: nrpe_mode is defined and nrpe_mode and inventory_hostname != icinga2_server
