---

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: ensure plugins directory exists
  file:
    dest: "{{ np }}"
    state: directory
    mode: '0755'

- block:
    - name: download extra plugins
      get_url:
        url: "{{ item.u }}"
        dest: "{{ np }}/{{ item.d }}"
        mode: '0755'
        checksum: "{{ item.c }}"
        validate_certs: "{{ item.v | default(true) }}"
      with_items: "{{ icinga2_plugins_extra }}"
  when: icinga2_plugins_extra is defined and icinga2_plugins_extra != []

- name: add dns service
  blockinfile:
    dest: /etc/icinga2/conf.d/services.conf
    block: |
      apply Service "DNS resolution - google" {
        import "generic-service"

        check_command = "dns"
        vars.dns_lookup = "$host_name$"
        vars.dns_server = "8.8.8.8"

        assign where "DNS-check" in host.groups

      }

      apply Service "DNS resolution - OpenDNS" {
        import "generic-service"

        check_command = "dns"
        vars.dns_lookup = "$host_name$"
        vars.dns_server = "208.67.222.222"

        assign where "DNS-check" in host.groups

      }

    marker: "# {mark} ANSIBLE MANAGED BLOCK - dns-check service"
    backup: yes

- name: add uptime service
  blockinfile:
    dest: /etc/icinga2/conf.d/services.conf
    block: |
      apply Service "uptime" {
        import "generic-service"

        check_command = "snmp"
        vars.snmp_oid = "1.3.6.1.2.1.1.3.0"
        vars.snmp_miblist = "DISMAN-EVENT-MIB"

        assign where host.vars.snmp_community # noqa 602 - not ansible
      }

    marker: "# {mark} ANSIBLE MANAGED BLOCK - uptime service"
    backup: yes
