---

- set_fact:
    www_user: apache
    apache_svc: httpd
    apache_confdir: /etc/httpd/conf.d
    modsecurity_active: /etc/httpd/modsecurity.d/activated_rules
    icinga2_pki_userdir: icinga
    icinga2_vimsyntax: /usr/share/doc/icinga2-common-2.4.1/syntax
    pnp4nagios_apacheconf: /etc/httpd/conf.d/pnp4nagios.conf
    pnp4nagios_templatedir: /usr/share/nagios/html/pnp4nagios/templates

- name: Redhat | server | Install Icinga2 RPM key
  rpm_key: state=present key=http://packages.icinga.org/icinga.key
  register: pkg_result
  until: pkg_result is success
- name: bootstrap ICINGA-release.repo
  get_url: url=http://packages.icinga.org/epel/ICINGA-release.repo
        dest=/etc/yum.repos.d/ICINGA-release.repo
        owner=root group=root mode=0644
- name: ICINGA-release repository enable
  ini_file: dest=/etc/yum.repos.d/ICINGA-release.repo
            section="icinga-stable-release"
            option=enabled
            value=1
- name: Redhat | Install icinga2 packages
  yum: name={{ icinga2_server_deps }} state=present update_cache=yes
  register: pkg_result
  until: pkg_result is success
- name: Redhat | Ensure services are started
  service: "name={{ item }} state=started"
  with_items:
#    - httpd
    - mariadb
#    - icinga2
## interactive only
#- name: Redhat | Ensure mysql secure install
#  command: mysql_secure_installation
#  when: ansible_os_family == "RedHat"
- stat: path=/root/.my.cnf
  register: rootmycnf
- name: Creating default .my.cnf
  lineinfile: dest=/root/.my.cnf line={{ item }} create=yes
  with_items:
    - "[client]"
    - "user=root"
#    - "password=root"
  when: not rootmycnf.stat.exists
- name: Ensure .my.cnf has a client section
  ini_file: dest=/root/.my.cnf
            section=client
            option={{ item.o }}
            value={{ item.v }}
            backup=yes
  with_items:
    - { o: user, v: root }
#    - { o: password, v: root }
  when: rootmycnf.stat.exists
## FIXME! fails 'ConfigParser.NoSectionError: No section: 'client'' like https://github.com/ansible/ansible/issues/8915
- mysql_user:
    name: "{{ icinga2_mysqlidouser }}"
    password: "{{ icinga2_mysqlidopass }}"
    priv: "{{ icinga2_mysqlidodb }}.*:SELECT,INSERT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"
    state: present
- mysql_db: name=icinga2
- mysql_db: name=icinga2 state=import target=/usr/share/icinga2-ido-mysql/schema/mysql.sql
  ignore_errors: true

- name: Enforce Timezone in php.ini
  replace: "dest=/etc/php.ini regexp='^;date.timezone =' replace='date.timezone = {{ tz }}'"

- name: Redhat | Ensure services are enabled
  service: "name={{ item }} enabled=yes"
  with_items:
    - httpd
    - mariadb
    - icinga2
  when: ansible_os_family == "RedHat"
