---

- set_fact:
    www_user: www-data
    apache_svc: apache2
    apache_confdir: /etc/apache2/conf-available
    modsecurity_active: /usr/share/modsecurity-crs/activated_rules
    icinga2_pki_userdir: nagios
    icinga2_vimsyntax: /usr/share/icinga2-common/syntax
    pnp4nagios_apacheconf: /etc/pnp4nagios/apache.conf
    pnp4nagios_templatedir: /etc/pnp4nagios/templates.d

## FIXME! all debconf except one are changed at each execution, how to make idempotent?
- name: Debian | server | set debconf configuration
  debconf: "name={{ item.name }} question={{ item.question }} value={{ item.value }} vtype={{ item.vtype }}"
  with_items:
    - { name: 'mysql-server-5.5', question: 'mysql-server/root_password', value: "{{ icinga2_mysqlrootpw }}", vtype: 'password' }
    - { name: 'mysql-server-5.5', question: 'mysql-server/root_password_again', value: "{{ icinga2_mysqlrootpw }}", vtype: 'password' }
    - { name: 'icinga2-ido-mysql', question: 'icinga2-ido-mysql/mysql/admin-pass', value: "{{ icinga2_mysqlrootpw }}", vtype: 'password' }
### FIXME! default user is still 'icinga2-ido-mysq' and db icinga2idomysql, pass does not seem to be updated
    - { name: 'icinga2-ido-mysql', question: 'icinga2-ido-mysql/db/dbname', value: "{{ icinga2_mysqlidodb }}", vtype: 'string' }
    - { name: 'icinga2-ido-mysql', question: 'icinga2-ido-mysql/mysql/app-pass', value: "{{ icinga2_mysqlidopass }}", vtype: 'password' }
    - { name: 'icinga2-ido-mysql', question: 'icinga2-ido-mysql/mysql/app-password-confirm', value: "{{ icinga2_mysqlidopass }}", vtype: 'password' }

- name: Debian | Server dependencies install
  apt: name={{item}} state=present update_cache=yes
  with_items: "{{ icinga2_server_deps }}"
- name: Debian | Extra packages install
  apt: name={{item}} state=present install_recommends=no
  with_items:
    - nagios-nrpe-plugin

- name: Ubuntu i386/x86_64 | add icinga packages repository key
  apt_key: url=http://packages.icinga.org/icinga.key state=present
  when: ansible_distribution == 'Ubuntu' and (ansible_architecture == 'i386' or ansible_architecture == 'x86_64')

- name: Ubuntu i386/x86_64 | add icinga packages repository
  apt_repository: repo='deb http://packages.icinga.org/ubuntu icinga-{{ ansible_distribution_release }} main' state=present
  when: ansible_distribution == 'Ubuntu' and (ansible_architecture == 'i386' or ansible_architecture == 'x86_64')

- name: Debian | Extra packages install
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - icinga2
    - icinga2-ido-mysql
    - git
    - icingaweb2
  when: ansible_distribution == 'Ubuntu' and (ansible_architecture == 'i386' or ansible_architecture == 'x86_64')

- name: Debian 386/x86_64 | Extra packages install
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - icinga2
    - icinga2-classicui
    - icingaweb2
  when: ansible_distribution == 'Debian' and (ansible_architecture == 'i386' or ansible_architecture == 'x86_64')

- name: Raspbian | add icinga packages repository
  apt_repository: repo='deb http://packages.icinga.org/raspbian icinga-wheezy main' state=present
  when: ansible_distribution == 'Debian' and (ansible_architecture == 'armhf' or ansible_architecture == 'armv7l')
- name: Raspbian | add icinga packages repository key
  apt_key: url=http://packages.icinga.org/icinga.key state=present
  when: ansible_distribution == 'Debian' and (ansible_architecture == 'armhf' or ansible_architecture == 'armv7l')
- name: Raspbian | Extra packages install
  apt: name={{item}} state=present update_cache=yes force=yes
  with_items:
    - icinga2
    - icinga2-ido-mysql
  when: ansible_distribution == 'Debian' and (ansible_architecture == 'armhf' or ansible_architecture == 'armv7l')

- apache2_module: name=rewrite state=present

- stat: path=/etc/apache2/sites-available/000-default.conf
  register: apachedefault
- replace: dest=/etc/apache2/sites-available/000-default.conf regexp='#ServerName www.example.com' replace="ServerName {{ ansible_fqdn }}" backup=yes
  when: apachedefault.stat.exists
- name: a2enconf icingaweb2
  file: src=/etc/apache2/conf-available/icingaweb2.conf dest=/etc/apache2/conf-enabled/icingaweb2.conf state=link
  notify:
    - restart apache
- name: a2disconf serve-cgi-bin.conf
#  file: src=/etc/apache2/sites-available/000-default.conf dest=/etc/apache2/sites-enabled/000-default.conf state=link
  file: dest=/etc/apache2/sites-enabled/000-default.conf state=absent
  when: apachedefault.stat.exists
  notify:
    - restart apache
- name: a2disconf serve-cgi-bin.conf
  file: dest=/etc/apache2/conf-enabled/serve-cgi-bin.conf state=absent
  notify:
    - restart apache
- name: a2disconf javascript-common.conf
  file: dest=/etc/apache2/conf-enabled/javascript-common.conf state=absent
  notify:
    - restart apache
- lineinfile: dest=/etc/apache2/conf-enabled/servername.conf line="ServerName {{ ansible_fqdn }}" create=yes
  notify:
    - restart apache

- name: Enforce Timezone in php.ini
  replace: "dest={{ icinga2_phpconf }}/apache2/php.ini regexp='^;date.timezone =' replace='date.timezone = {{ tz }}'"

- name: Debian | Ensure services are enabled
  service: "name={{ item }} enabled=yes"
  with_items:
    - icinga2
    - apache2

