---

- name: ensure .vim directories exist - non-root user
  file: dest={{ item }} state=directory mode=0700
  with_items:
    - /home/{{ icinga2_user }}/.vim/syntax
    - /home/{{ icinga2_user }}/.vim/ftdetect
  when: icinga2_user != 'root' and icinga2_user != '_icinga2'

- name: replicate icinga2 vim syntax file (1) - non-root
  copy:
    src: "{{ icinga2_vimsyntax }}/vim/syntax/icinga2.vim"
    dest: "/home/{{ icinga2_user }}/.vim/syntax/"
    remote_src: true
  when: icinga2_user != 'root' and icinga2_user != '_icinga2'

- name: replicate icinga2 vim syntax file (2) - non-root
  copy:
    src: "{{ icinga2_vimsyntax }}/vim/ftdetect/icinga2.vim"
    dest: "/home/{{ icinga2_user }}/.vim/ftdetect/"
    remote_src: true
  when: icinga2_user != 'root' and icinga2_user != '_icinga2'

- name: ensure .vim directories exist - root user
  file: dest={{ item }} state=directory mode=0700
  with_items:
    - /root/.vim/syntax
    - /root/.vim/ftdetect
  when: icinga2_user == 'root'
